---
- name: Install (Cask-provided) Tools
  homebrew_cask:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "Darwin"
  with_items:
    - 'alfred'
    - '1password'
    - 'magicprefs'
    - 'apache-directory-studio'
    - 'slack'
    - 'vagrant'
    - 'virtualbox'
    - 'minikube'
    - 'blue-jeans'
    - 'textmate'
    - 'docker'
    - 'sourcetree'
    - 'irccloud'
    - 'visual-studio-code'
    - 'blue-jeans'
    - 'google-cloud-sdk'
    - 'colloquy'


- name: Install (Homebrew-provided) Productivity Tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - 'git'
    - 'which'
    - 'fzf'
    - 'yq'
    - 'jq'
    - 'kubernetes-cli'
    - 'openshift-cli'
    - 'terraform'
    - 'vim'
    - 'curl'
    - 'wget'
    - 'gpg'
    - 'irssi'
    - 'kubectx'
    - 'kube-ps1'
    - 'pandoc'
    - 'asciinema'
    - 'markdown'
    - 'dive'
