---
- name: Install (Cask-provided) Tools
  homebrew_cask:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == "Darwin"
  with_items:
    - '1password'
    - 'alfred'
    - 'apache-directory-studio'
    - 'blue-jeans'
    - 'blue-jeans'
    - 'colloquy'
    - 'docker-edge'
    - 'google-cloud-sdk'
    - 'irccloud'
    - 'iterm2'
    - 'magicprefs'
    - 'minikube'
    - 'slack'
    - 'sourcetree'
    - 'textmate'
    - 'vagrant'
    - 'virtualbox'
    - 'visual-studio-code'

- name: Install (Homebrew-provided) Productivity Tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - 'asciinema'
    - 'awscli'
    - 'bash-completion'
    - 'coreutils'
    - 'curl'
    - 'dive'
    - 'docker-compose'
    - 'docker-machine'
    - 'fzf'
    - 'git'
    - 'gpg'
    - 'irssi'
    - 'jq'
    - 'jsonnet'
    - 'kube-ps1'
    - 'kubectx'
    - 'kubernetes-cli'
    - 'markdown'
    - 'openshift-cli'
    - 'operator-sdk'
    - 'packer'
    - 'pandoc'
    - 'pinentry'
    - 'skopeo'
    - 'socat'
    - 'terraform'
    - 'tree'
    - 'vim'
    - 'watch'
    - 'wget'
    - 'which'
    - 'yamllint'
    - 'yq'

- name: Tap cblecker/ocm 
  homebrew_tap:
    tap: 'cblecker/tap/ocm'
    url: 'https://github.com/cblecker/homebrew-tap'

- name: Worklog tool for Wiki
  git:
    repo: 'https://github.com/lisa/worklog.git'
    dest: "/Users/{{ lookup('env', 'USER') }}/go/src/github.com/lisa/worklog"
